In [5]:
import numpy as np
import cvxopt

P = cvxopt.matrix(np.array([[2,1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))

sol = cvxopt.solvers.qp(P, q)

print(sol)
# 最適解
print(np.array(sol["x"]))
# 最適解の時の目的関数の値
print(np.array(sol["primal objective"]))

{'status': 'optimal', 'x': <2x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 'z': <0x1 matrix, tc='d'>, 's': <0x1 matrix, tc='d'>, 'gap': 0.0, 'relgap': 0.0, 'primal objective': -4.0, 'dual objective': -4.0, 'primal slack': 0.0, 'dual slack': 0.0, 'primal infeasibility': 0.0, 'dual infeasibility': 1.9860273225978183e-16, 'iterations': 0}
[[ 1.57009246e-16]
 [-2.00000000e+00]]
-4.0


In [8]:
import numpy as np
import cvxopt

P = cvxopt.matrix(np.array([[2,1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
A = cvxopt.matrix(np.array([[1, 1]], dtype=np.float64))
b = cvxopt.matrix(np.array([0], dtype=np.float64))

sol = cvxopt.solvers.qp(P, q, A=A, b=b)

print(A)
print(b)
print(sol)
# 最適解
print(np.array(sol["x"]))
# 最適解の時の目的関数の値
print(np.array(sol["primal objective"]))

[ 1.00e+00  1.00e+00]

[ 0.00e+00]

{'status': 'optimal', 'x': <2x1 matrix, tc='d'>, 'y': <1x1 matrix, tc='d'>, 'z': <0x1 matrix, tc='d'>, 's': <0x1 matrix, tc='d'>, 'gap': 0.0, 'relgap': 0.0, 'primal objective': -1.0000000000000013, 'dual objective': -1.0000000000000013, 'primal slack': 0.0, 'dual slack': 0.0, 'primal infeasibility': 4.440892098500626e-16, 'dual infeasibility': 9.930136612989092e-17, 'iterations': 0}
[[ 1.]
 [-1.]]
-1.0000000000000013


In [9]:
import numpy as np
import cvxopt

P = cvxopt.matrix(np.array([[2,1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
G = cvxopt.matrix(np.array([[2, 3]], dtype=np.float64))
h = cvxopt.matrix(np.array([3], dtype=np.float64))

sol = cvxopt.solvers.qp(P, q, G=G, h=h)

print(sol)
# 最適解
print(np.array(sol["x"]))
# 最適解の時の目的関数の値
print(np.array(sol["primal objective"]))

     pcost       dcost       gap    pres   dres
 0:  1.8858e+00  2.9758e-01  2e+00  0e+00  2e+00
 1: -2.1066e+00 -2.1546e+00  5e-02  2e-16  7e-01
 2: -3.9999e+00 -4.0665e+00  7e-02  6e-16  8e-17
 3: -4.0000e+00 -4.0007e+00  7e-04  9e-16  1e-16
 4: -4.0000e+00 -4.0000e+00  7e-06  3e-16  6e-17
 5: -4.0000e+00 -4.0000e+00  7e-08  3e-16  2e-16
Optimal solution found.
{'x': <2x1 matrix, tc='d'>, 'y': <0x1 matrix, tc='d'>, 's': <1x1 matrix, tc='d'>, 'z': <1x1 matrix, tc='d'>, 'status': 'optimal', 'gap': 6.640383992941244e-08, 'relative gap': 1.660095998235311e-08, 'primal objective': -4.0, 'dual objective': -4.00000006640384, 'primal infeasibility': 2.9605947323337506e-16, 'dual infeasibility': 2.0202423019149744e-16, 'primal slack': 9.00000003443162, 'dual slack': 7.378204408374322e-09, 'iterations': 5}
[[-2.45940165e-09]
 [-2.00000001e+00]]
-4.0
